#!/usr/bin/env bash
# script that configures an Ubuntu server to resolve localhost and facebook.com to other addresses

sed -i '/127\.0\.0\.1\s\+/localhost/d' /etc/hosts
sed -i '/facebook\.com/d' /etc/hosts

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
